### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by zuca2682** [zuca2682/protospace-33475#1]
# URL
https://protospace-33475.herokuapp.com/

**Comment by Uri-sayaka** [comment]
zuca2682 さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
プロトタイプ詳細ページにおいて、『ログイン・ログアウトの状態に関わらず、プロダクトの情報（プロトタイプ名・投稿者・画像・キャッチコピー・コンセプト）が表示されていること』が正しいのですが、『プロトタイプ名』が表示できない状態となっております。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by zuca2682** [comment]
ご対応いただきありがとうございます。
ただいま修正を行い、プロトタイプ名が表示されるようになりました。
ご確認のほどよろしくお願いいたします。

**Comment by Uri-sayaka** [comment]
zuca2682 さん、ご提出ありがとうございます！
上記本番環境に反映されていないようです。
再度ご確認いただければ幸いです。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by zuca2682** [comment]
大変失礼いたしました。
本番環境に反映され、プロトタイプ詳細ページにてプロトタイプ名が表示されるようになったのを確認いたしました。
引き続きご確認のほどよろしくお願いいたします。

**Comment by Uri-sayaka** [comment]
zuca2682 さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
